# config/packages/security.yaml
security:
    # ...
    providers:
        # Define a user provider that uses the User entity
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email # ou email, selon ce que vous utilisez pour l'authentification

    firewalls:
        main:
            form_login:
                login_path: signin
                check_path: signin
                enable_csrf: true
                csrf_token_id: authenticate
                csrf_parameter: _csrf_token
                username_parameter: email
                password_parameter: password
                default_target_path: admin_dashboard  # Spécifiez la route du tableau de bord ici
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
    access_control:
        # Assurez-vous que seuls les utilisateurs authentifiés peuvent accéder à la route 'dashboard'
        #- { path: ^/dashboard, roles: ROLE_USER }
        # Ajoutez d'autres règles d'accès si nécessaire

