vich_uploader:
    db_driver: orm
    mappings:
        contrat_pdf:
            uri_prefix: /uploads/pdf
            upload_destination: '%kernel.project_dir%/public/uploads/pdf'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
